---
vc_fact_domain: "vsphere.local"
vc_fact_ntp: "10.0.77.54"
vc_fact_password: "{{ lookup('ansible.builtin.env', 'VCESXIPASSWORD') }}"
vc_fact_datacenter1: "nested-devqedatacenter-1"
vc_fact_datacenter2: "nested-devqedatacenter-2"
vc_fact_cluster1: "nested-devqecluster-1"
vc_fact_cluster2: "nested-devqecluster-2"
vc_fact_deployment_network: "devqe-922"
vc_fact_deployment_network2: "devqe-922"
vc_hostname: "{{ lookup('ansible.builtin.env', 'VMWARE_HOST') }}"
vc_username: "{{ lookup('ansible.builtin.env', 'VMWARE_USER') }}"
vc_password: "{{ lookup('ansible.builtin.env', 'VMWARE_PASSWORD') }}"
vc_datacenter: "devqedatacenter-1"
vc_cluster: "devqecluster-1"
vc_folder: "nested-limited"
